[2023-04-23 21:22:31,905] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:22:31] "[35m[1mDELETE /valve?nome=TESTE HTTP/1.1[0m" 500 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:30:27,606] INFO _log() L224  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.9:5000 - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:30:27,608] INFO _log() L224  [33mPress CTRL+C to quit[0m - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:30:29,833] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:30:29] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:30:30,059] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:30:30] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:30:32,279] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:30:32] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:30:32,328] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:30:32] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:30:32,329] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:30:32] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:30:32,977] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:30:32] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:30:33,030] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:30:33] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:30:33,054] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:30:33] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:30:33,057] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:30:33] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:30:33,702] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:30:33] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:30:46,040] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:30:46] "POST /valve HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:31:10,744] WARNING del_valve() L116  Erro ao remover válvula de nome Teste, Válvula não encontrada. - call_trace=C:\Users\Pedro Serrano\Dados\Pós\engenharia-de-software-main\MVP\projeto_mvp_1\app.py L116 
[2023-04-23 21:31:10,746] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:31:10] "[33mDELETE /valve?nome=Teste HTTP/1.1[0m" 404 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:31:17,257] ERROR log_exception() L1744 Exception on /valve [DELETE] - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py L1744
Traceback (most recent call last):
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2137, in make_response
    raise TypeError(
TypeError: The view function for 'del_valve' did not return a valid response. The function either returned None or ended without a return statement.
[2023-04-23 21:31:17,262] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:31:17] "[35m[1mDELETE /valve?nome=TESTE HTTP/1.1[0m" 500 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:32:02,795] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:32:02] "POST /valve HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:32:17,184] ERROR log_exception() L1744 Exception on /valve [DELETE] - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py L1744
Traceback (most recent call last):
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2137, in make_response
    raise TypeError(
TypeError: The view function for 'del_valve' did not return a valid response. The function either returned None or ended without a return statement.
[2023-04-23 21:32:17,189] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:32:17] "[35m[1mDELETE /valve?nome=TESTE HTTP/1.1[0m" 500 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:33:45,213] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:33:45] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:33:45,272] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:33:45] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:33:45,300] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:33:45] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:33:45,301] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:33:45] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:33:46,610] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:33:46] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:33:46,730] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:33:46] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:33:57,929] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:33:57] "POST /valve HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 21:33:58,903] WARNING add_valve() L63   Erro ao adicionar válvula 'TESTE', Válvula de mesmo nome já salva na base :/ - call_trace=C:\Users\Pedro Serrano\Dados\Pós\engenharia-de-software-main\MVP\projeto_mvp_1\app.py L63  
[2023-04-23 21:33:58,906] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 21:33:58] "[31m[1mPOST /valve HTTP/1.1[0m" 409 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
